[package]
name = "semverator"
version = "0.5.1"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
description = "A command line tool for working with semantic versioning (libpkgx implementation)"
homepage = "https://github.com/jhheider/semverator"
repository = "https://github.com/jhheider/semverator"
keywords = ["semver", "semantic", "versioning", "pkgx"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.75"
clap = { version = '4.4.2', features = ['cargo'] }
regex = "1.9.5"
libsemverator = { path = "../lib" }
