# https://github.com/BamPeers/rust-ci-github-actions-workflow

on:
  release:
    types: [published]

name: Release Packaging

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: semverator
      RUSTFLAGS: "-D warnings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: katyo/publish-crates@v2
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}