name: Style

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    uses: jhheider/rust-ci/.github/workflows/style.yml@v1
