# https://github.com/BamPeers/rust-ci-github-actions-workflow

on:
  pull_request:
  push:
    branches:
      - main

name: Test with Code Coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Test (${{ matrix.os }})
    env:
      PROJECT_NAME_UNDERSCORE: semverator
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort -D warnings
      RUSTDOCFLAGS: -Cpanic=abort
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
      - name: Test
        run: cargo test --all-features
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
      - name: Setup just
        uses: extractions/setup-just@v3
      - run: cargo install cargo-tarpaulin
      - name: Generate test result and coverage report
        run: just coverage
      - uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage/lcov.info
